### PR TITLE
Feat: Tazama Relay Service

### PR DESCRIPTION
**Pull request by UmairKhan-Paysys**
Tazama Relay Service for enabling TMS to relay messages to the desired destination (NATS, RabbitMQ, REST API).
The service needs a .env file for configuration and setting the desired destination. Please use the .env.template provided for reference. For deployment the Dockerfile will also require updates accordingly.
Further details are mentioned in the README.md, otherwise please feel free to reach out.

### CODE REVIEW

**Review by Lenbkr — CHANGES_REQUESTED** [review]
Project Structure

1. The dist folder should be deleted from git. 
2. The tsconfig.json is not aligned with the rest of Tazama, check event-director as example. Specifically module system to use nodenext over commonjs for better compatibility and overall a more modern approach
3. The dockerfile is based on an older node version, current LTS version of Nodejs is v20 (v22 real soon) so be sure to update and test that it works newer versions.
4. Project has no eslint set up. Once again event-director would be a good example for the config used (eslint.config.mjs). Just be sure to stick to eslint v8 as v9 still doesn't yet support the all the plugin in use yet. Use the eslint and plugins from event-director and their versions.
5. No Pre-commit and pre-push hooks. Husky and lint-staged is used. Example in event-director.


Code Recommendations
1. The standard is make use of the protobuf for serialization and deserialization of network communication. Specifically deserialization is needed.
2. The frms-coe-lib has a loggerservice used throughout the platform for it's sidecart logging functionality in addition to it's protobuf capabilities.

**Comment by UsamaAbdulMannan** [comment]
@Lenbkr @Sandy-at-Tazama,

Based on our recent discussion, could you please acknowledge the below-mentioned items as CR? So that we can start working on it accordingly:
1. If Destination is REST API, implement a option to "Deserialize".
2. Add Logger service
-     a. For logging, the deserialization and logging part should happen asynchronously (so as not to affect performance)
-     b. Log with proper level - Error and Exceptions separate and Verbose logging separate

**Comment by Sandy-at-Tazama** [comment]
@UsamaAbdulMannan 

Use logging library (contributing guide updated https://github.com/tazama-lf/.github/blob/main/CONTRIBUTING.md)
https://github.com/tazama-lf/frms-coe-lib/blob/dev/README.md 
"@tazama-lf/frms-coe-lib": "5.0.0-rc.4"

a. For logging, the deserialization and logging part should happen asynchronously (so as not to affect performance)
b. Log with proper level - Error and Exceptions separate and Verbose logging separate including msgId (from deserialised message)

**Review by Lenbkr — CHANGES_REQUESTED** [review]
Looks good. 

Just clean up the 'src/utils' folder which contains files no longer referenced anywhere.

**Review by Lenbkr — APPROVED** [review]

**Review by Justus-at-Tazama — APPROVED** [review]

**Pull request merged**
